server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # 服务调用链路监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样值介于 0 - 1 之间, 1 则表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xuyang
    password: 12345

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: run.xuyang.springcloud.entity

springdoc:
  api-docs:
    # 开启文档
    enabled: true
  # 扫描的包名
  packages-to-scan: run.xuyang.springcloud
  # 自定义接口文档的地址
  swagger-ui:
    path: /swagger-doc

eureka:
  client:
    # 表示是否将自己注册进 EurekaServer, 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息, 默认为 true。单节点无所谓,
    # 集群必须设置为 true 才能配合 Ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机版
      defaultZone: http://localhost:7001/eureka
  instance:
    # 配置这个可以修改显示的主机名
    instance-id: payment8001
    # 开启后服务访问路径可以显示 ip 地址
    prefer-ip-address: true
    # Eureka 客户端向服务端发送心跳的时间间隔, 单位为秒(默认是 30s)
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后等待的时间上线,单位为秒(默认是 90s), 超时将剔除服务
    lease-expiration-duration-in-seconds: 2
